---
development:
  cloud_name: <%= ENV['CLOUDINARY_CLOUD_NAME'] %>
  api_key: <%= ENV['CLOUDINARY_API_KEY']%>
  api_secret: <%= ENV['CLOUDINARY_SECRET_KEY']%>
  enhance_image_tag: true
  static_file_support: false
production:
  cloud_name: <%= ENV['CLOUDINARY_CLOUD_NAME']%>
  api_key: <%= ENV['CLOUDINARY_API_KEY']%>
  api_secret: <%= ENV['CLOUDINARY_SECRET_KEY']%>
  enhance_image_tag: true
  static_file_support: true
test:
  cloud_name: <%= ENV['CLOUDINARY_CLOUD_NAME']%>
  api_key: <%= ENV['CLOUDINARY_API_KEY']%>
  api_secret: <%= ENV['CLOUDINARY_SECRET_KEY']%>
  enhance_image_tag: true
  static_file_support: false
